title: UFO sightings map
hero_image: images/banner.png
description: Plot UFO sightings from a CSV file on an interactive world map
meta_title: Python coding projects for kids and teens | UFO sightings map
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Plot UFO sightings from a CSV file on an interactive world map and click markers to explore the data.
version: 4
listed: true
copyedit: true
last_tested: '2026-01-14'
landing: true
steps:
  - title: Load and display the map
  - title: Test coordinate conversion with one marker
    completion:
      - engaged
  - title: Load UFO data from the CSV file
    completion:
      - internal
  - title: Plot all sightings as simple dots
  - title: Draw different markers for different UFO shapes
    completion:
      - external
  - title: "Challenge: Improve the interaction"
    challenge: true
